repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements

- repo: local
  hooks:
  - id: linting
    name: Run Linters (flake8)
    entry: flake8
    language: system
    types: [python]

  - id: testing
    name: Run Tests (pytest)
    entry: pytest
    pass_filenames: false
    always_run: true
    language: system
    types: [python]
    stages: [pre-merge-commit, pre-push]
